Repository LDSSA/portal, pull requests merged in 2023-09, with the labels that each got.

#265 [#264] Docs: Migrate Read the Docs project configuration to v2
  .gitignore
  .readthedocs.yaml
  README.md
  docs/Makefile
  docs/administration.rst
  docs/conf.py
  docs/hackathon_02.rst
  docs/index.rst
  docs/make.bat
  docs/setup.rst
  docs/source/__init__.py
  docs/source/administration.rst
  docs/source/assets/1.png
  docs/source/assets/2.png
  docs/source/assets/3.png
  docs/source/assets/4.png
  docs/source/assets/administration/1.png
  docs/source/assets/administration/2.png
  docs/source/assets/administration/3.png
  docs/source/assets/learning_units.png
  docs/source/backup.rst
  docs/source/conf.py
  docs/source/deploy.rst
  docs/source/hackathon_02.rst
  docs/source/index.rst
  docs/source/logs.rst
  docs/source/running.rst
  docs/source/setup.rst
  docs/source/structure.rst
  docs/source/tests.rst
  docs/structure.rst
  docs/tests.rst
  poetry.lock
  pyproject.toml
Labels: documentation, portal

#267 [#266] Fix: Remove linkcheck job from the readthedocs config
  .readthedocs.yaml
Labels: bugfix, documentation, portal

#272 Documentation: reset portal database
  docs/source/index.rst
  docs/source/resetdb.rst
Labels: documentation
